services:
  - type: web
    name: videosnap-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_KEY
        value: gizli_anahtar_buraya_yaz
